from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from pipeline.config import NATIONAL_TREASURES_DIR
from pipeline.hgl_generator import HglGenerator


_FALLBACK_ARTIFACTS = [
    {
        "ccbaMnm1": "흥인지문",
        "ccbaMnm2": "Heunginjimun Gate",
        "ccbaKdcd": "11",
        "ccbaAsno": "0001",
        "ccbsChrcd": "조선시대",
        "ccmiName": "석재, 목재",
        "ccmaName": "서울특별시 종로구",
        "ccbaClas": "유적건조물",
        "ccbaCncl": "조선시대 한양 도성의 동쪽 대문으로, 흥인지문이라고도 불린다.",
        "ccbaImage": "/images/relic/11/0001.jpg",
        "ccbaSize": "정면 5칸, 측면 2칸",
    },
    {
        "ccbaMnm1": "원각사지십층석탑",
        "ccbaMnm2": "Wonkyo Temple Ten-story Stone Pagoda",
        "ccbaKdcd": "11",
        "ccbaAsno": "0002",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "화강암",
        "ccmaName": "서울특별시 종로구",
        "ccbaClas": "불교 관련 석조물",
        "ccbaCncl": "신라 원각사지에서 발견된 십층석탑으로, 통일신라 시대의 대표적인 석탑이다.",
        "ccbaImage": "/images/relic/11/0002.jpg",
        "ccbaSize": "높이 8.3m",
    },
    {
        "ccbaMnm1": "북한산신라진흥왕순수비",
        "ccbaMnm2": "Silla King Jinheung's Mausoleum Stone",
        "ccbaKdcd": "11",
        "ccbaAsno": "0003",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "화강암",
        "ccmaName": "서울특별시 강북구",
        "ccbaClas": "순수비",
        "ccbaCncl": "북한산에 있는 신라진흥왕의 순수비로, 통일신라 시대의 중요한 역사 자료이다.",
        "ccbaImage": "/images/relic/11/0003.jpg",
        "ccbaSize": "높이 1.8m",
    },
    {
        "ccbaMnm1": "금동대향로",
        "ccbaMnm2": "Gilt-bronze Censer",
        "ccbaKdcd": "11",
        "ccbaAsno": "0068",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금동",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "불교 신앙器材",
        "ccbaCncl": "삼국시대 금동으로 제작된 대형 향로로, 한국 불교 예술의 정수라 평가받는다.",
        "ccbaImage": "/images/relic/11/0068.jpg",
        "ccbaSize": "높이 64.2cm",
    },
    {
        "ccbaMnm1": "금동미륵보살반가사유상",
        "ccbaMnm2": "Gilt-bronze Maitreya Bodhisattva in Pensive Posture",
        "ccbaKdcd": "11",
        "ccbaAsno": "0078",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금동",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "불교 조각",
        "ccbaCncl": "삼국시대 금동으로 제작된 미륵보살 반가사유상으로, 한 손을 턱에 괴고 사유의 자세로 앉아 있다.",
        "ccbaImage": "/images/relic/11/0078.jpg",
        "ccbaSize": "높이 93.5cm",
    },
    {
        "ccbaMnm1": "금동미륵보살반가사유상",
        "ccbaMnm2": "Gilt-bronze Maitreya Bodhisattva in Pensive Posture",
        "ccbaKdcd": "11",
        "ccbaAsno": "0083",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금동",
        "ccmaName": "경주국립박물관",
        "ccbaClas": "불교 조각",
        "ccbaCncl": "삼산관에서 발견된 삼국시대 금동 미륵보살 반가사유상으로, 예술성이 뛰어나다.",
        "ccbaImage": "/images/relic/11/0083.jpg",
        "ccbaSize": "높이 55.5cm",
    },
    {
        "ccbaMnm1": "금강계류금강봉",
        "ccbaMnm2": "Geumgang Yeongnu Geumgang Peak",
        "ccbaKdcd": "11",
        "ccbaAsno": "0010",
        "ccbsChrcd": "조선시대",
        "ccmiName": "종이, 채색",
        "ccmaName": "궁능중앙박물관",
        "ccbaClas": "민화",
        "ccbaCncl": "조선시대 금강산을 그린 계류도로, 민화의 걸작이다.",
        "ccbaImage": "/images/relic/11/0010.jpg",
        "ccbaSize": "가로 137cm, 세로 71cm",
    },
    {
        "ccbaMnm1": "동양최초의 금속활자",
        "ccbaMnm2": "World's Earliest Metal Movable Type",
        "ccbaKdcd": "11",
        "ccbaAsno": "0011",
        "ccbsChrcd": "고려시대",
        "ccmiName": "청동",
        "ccmaName": "한국국학진흥원",
        "ccbaClas": "전적류",
        "ccbaCncl": "고려 몽골 고려에서 사용된 세계 최초의 금속활자로, 인쇄술사에 큰 영향을 미쳤다.",
        "ccbaImage": "/images/relic/11/0011.jpg",
        "ccbaSize": "가로 6.3cm, 세로 9.5cm",
    },
    {
        "ccbaMnm1": "평창대관도",
        "ccbaMnm2": "Pyeongchang Daegwando",
        "ccbaKdcd": "11",
        "ccbaAsno": "0006",
        "ccbsChrcd": "조선시대",
        "ccmiName": "종이, 채색",
        "ccmaName": "한국민속박물관",
        "ccbaClas": "지형도",
        "ccbaCncl": "조선시대 강원도 평창 지역을 그린 대관도로, 역사 지리학적으로 중요하다.",
        "ccbaImage": "/images/relic/11/0006.jpg",
        "ccbaSize": "가로 180cm, 세로 380cm",
    },
    {
        "ccbaMnm1": "용두사지석등",
        "ccbaMnm2": "Yongdusa Temple Stone Lantern",
        "ccbaKdcd": "11",
        "ccbaAsno": "0009",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "화강암",
        "ccmaName": "경주국립박물관",
        "ccbaClas": "불교 관련 석조물",
        "ccbaCncl": "신라 용두사지에서 발견된 석등으로, 통일신라 시대의 정형화된 불교 예술을 보여준다.",
        "ccbaImage": "/images/relic/11/0009.jpg",
        "ccbaSize": "높이 60cm",
    },
    {
        "ccbaMnm1": "청자 어eletronic",
        "ccbaMnm2": "Celadon with Crane and Cloud Design",
        "ccbaKdcd": "11",
        "ccbaAsno": "0065",
        "ccbsChrcd": "고려시대",
        "ccmiName": "청자",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "도자기",
        "ccbaCncl": "고려시대의 대표적인 청자로, 학문雲文이 정교하게 표현된 작품이다.",
        "ccbaImage": "/images/relic/11/0065.jpg",
        "ccbaSize": "높이 22.8cm",
    },
    {
        "ccbaMnm1": "분청사자수도완",
        "ccbaMnm2": "Underglaze-blue White Porcelain Bottle",
        "ccbaKdcd": "11",
        "ccbaAsno": "0067",
        "ccbsChrcd": "조선시대",
        "ccmiName": "백토, 안료",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "도자기",
        "ccbaCncl": "조선시대의 분청사기로, 청자색 그림자가 특징적인 독특한 작품이다.",
        "ccbaImage": "/images/relic/11/0067.jpg",
        "ccbaSize": "높이 18.2cm",
    },
    {
        "ccbaMnm1": "금은화靴",
        "ccbaMnm2": "Gold and Silver Thread-woven Shoes",
        "ccbaKdcd": "11",
        "ccbaAsno": "0023",
        "ccbsChrcd": "고려시대",
        "ccmiName": "비단, 금은실",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "직물",
        "ccbaCncl": "고려시대의 직물로, 금은실을 사용하여 정교하게 제작되었다.",
        "ccbaImage": "/images/relic/11/0023.jpg",
        "ccbaSize": "길이 26cm",
    },
    {
        "ccbaMnm1": "불국사 다보탑",
        "ccbaMnm2": "Dabotap Pagoda of Bulguksa Temple",
        "ccbaKdcd": "11",
        "ccbaAsno": "0022",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "화강암",
        "ccmaName": "경주시",
        "ccbaClas": "불교 관련 석조물",
        "ccbaCncl": "불국사의 다보탑으로, 통일신라 시대의 대표적 석탑이다.",
        "ccbaImage": "/images/relic/11/0022.jpg",
        "ccbaSize": "높이 10.4m",
    },
    {
        "ccbaMnm1": "불국사 석가탑",
        "ccbaMnm2": "Seokgatap Pagoda of Bulguksa Temple",
        "ccbaKdcd": "11",
        "ccbaAsno": "0021",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "화강암",
        "ccmaName": "경주시",
        "ccbaClas": "불교 관련 석조물",
        "ccbaCncl": "불국사의 석가탑으로, 통일신라 시대의 오층석탑의 대표격이다.",
        "ccbaImage": "/images/relic/11/0021.jpg",
        "ccbaSize": "높이 8.2m",
    },
    {
        "ccbaMnm1": "첨성대",
        "ccbaMnm2": "Cheomseongdae Observatory",
        "ccbaKdcd": "11",
        "ccbaAsno": "0031",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "화강암",
        "ccmaName": "경주시",
        "ccbaClas": "과학·기술 유적",
        "ccbaCncl": "신라 시대의 천문 관측 대대로, 세계에서 가장 오래된 천문대 중 하나이다.",
        "ccbaImage": "/images/relic/11/0031.jpg",
        "ccbaSize": "높이 9.4m",
    },
    {
        "ccbaMnm1": "금강송이금관",
        "ccbaMnm2": "Gold Crown from Geumgang",
        "ccbaKdcd": "11",
        "ccbaAsno": "0087",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금, 은",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "금속공예",
        "ccbaCncl": "금강총에서 출토된 금관으로, 신라 왕실의 권위를 보여준다.",
        "ccbaImage": "/images/relic/11/0087.jpg",
        "ccbaSize": "높이 27.5cm",
    },
    {
        "ccbaMnm1": "금관",
        "ccbaMnm2": "Gold Crown",
        "ccbaKdcd": "11",
        "ccbaAsno": "0088",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금, 은",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "금속공예",
        "ccbaCncl": "신라 시대의 금관으로, 장식과 공예가 뛰어나다.",
        "ccbaImage": "/images/relic/11/0088.jpg",
        "ccbaSize": "높이 23.5cm",
    },
    {
        "ccbaMnm1": "금동용두보당",
        "ccbaMnm2": "Gilt-bronze Dragon Head Finial",
        "ccbaKdcd": "11",
        "ccbaAsno": "0136",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금동",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "금속공예",
        "ccbaCncl": "삼국시대 금동 용두보당으로, 용 문양이 정교하게 표현되었다.",
        "ccbaImage": "/images/relic/11/0136.jpg",
        "ccbaSize": "길이 85cm",
    },
    {
        "ccbaMnm1": "청동은입사포류수금문정병",
        "ccbaMnm2": "Bronze Inlaid Vessel with Phoenix and Dragon Design",
        "ccbaKdcd": "11",
        "ccbaAsno": "0092",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "청동",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "금속공예",
        "ccbaCncl": "삼국시대 청동 은입사 포류수금문정병으로, 정교한 은입사 기법이 특징이다.",
        "ccbaImage": "/images/relic/11/0092.jpg",
        "ccbaSize": "높이 28.5cm",
    },
    {
        "ccbaMnm1": "팔만대장경",
        "ccbaMnm2": "Palman Daejanggyeong",
        "ccbaKdcd": "11",
        "ccbaAsno": "0032",
        "ccbsChrcd": "고려시대",
        "ccmiName": "목판",
        "ccmaName": "해인사",
        "ccbaClas": "전적류",
        "ccbaCncl": "고려 팔만대장경으로, 세계 최대의 목판 인쇄물이자 유네스코 세계문화유산이다.",
        "ccbaImage": "/images/relic/11/0032.jpg",
        "ccbaSize": "가로 69.5cm, 세로 23.8cm",
    },
    {
        "ccbaMnm1": "조선왕조실록",
        "ccbaMnm2": "Annals of the Joseon Dynasty",
        "ccbaKdcd": "11",
        "ccbaAsno": "0131",
        "ccbsChrcd": "조선시대",
        "ccmiName": "종이, 먹",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "전적류",
        "ccbaCncl": "조선시대의 역대 왕의 실록으로, 약 900년간의 한국 역사를 기록한 세계 최대의 사서이다.",
        "ccbaImage": "/images/relic/11/0131.jpg",
        "ccbaSize": "가로 30.5cm, 세로 21cm",
    },
    {
        "ccbaMnm1": "경복사지 철기",
        "ccbaMnm2": "Iron Pagoda of Gyeongboksa Temple",
        "ccbaKdcd": "11",
        "ccbaAsno": "0041",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "철",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "불교 관련 철조물",
        "ccbaCncl": "삼국시대 철기로 제작된 기둥 구조물이다.",
        "ccbaImage": "/images/relic/11/0041.jpg",
        "ccbaSize": "높이 4.2m",
    },
    {
        "ccbaMnm1": "금동관음보살좌상",
        "ccbaMnm2": "Gilt-bronze Avalokitesvara Bodhisattva Seated Statue",
        "ccbaKdcd": "11",
        "ccbaAsno": "0089",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금동",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "불교 조각",
        "ccbaCncl": "삼국시대 금동으로 제작된 관음보살좌상으로, 조각이 정교하고 예술성이 높다.",
        "ccbaImage": "/images/relic/11/0089.jpg",
        "ccbaSize": "높이 71.2cm",
    },
    {
        "ccbaMnm1": "금동아미타여래좌상",
        "ccbaMnm2": "Gilt-bronze Amitabha Buddha Seated Statue",
        "ccbaKdcd": "11",
        "ccbaAsno": "0090",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금동",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "불교 조각",
        "ccbaCncl": "삼국시대 금동으로 제작된 아미타여래좌상으로, 불교 조각의 정수이다.",
        "ccbaImage": "/images/relic/11/0090.jpg",
        "ccbaSize": "높이 117cm",
    },
    {
        "ccbaMnm1": "금동药师如来立像",
        "ccbaMnm2": "Gilt-bronze Bhaisajyaguru Buddha Seated Statue",
        "ccbaKdcd": "11",
        "ccbaAsno": "0121",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금동",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "불교 조각",
        "ccbaCncl": "삼국시대 금동으로 제작된 약사여래좌상으로, 한국 불교 조각의 걸작이다.",
        "ccbaImage": "/images/relic/11/0121.jpg",
        "ccbaSize": "높이 109cm",
    },
    {
        "ccbaMnm1": "금동阿弥陀如来立像",
        "ccbaMnm2": "Gilt-bronze Amitabha Buddha Standing Statue",
        "ccbaKdcd": "11",
        "ccbaAsno": "0122",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금동",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "불교 조각",
        "ccbaCncl": "삼국시대 금동으로 제작된 아미타여래 입상이다.",
        "ccbaImage": "/images/relic/11/0122.jpg",
        "ccbaSize": "높이 104cm",
    },
    {
        "ccbaMnm1": "국립중앙박물관 소장 신라금관",
        "ccbaMnm2": "Silla Gold Crown at National Museum",
        "ccbaKdcd": "11",
        "ccbaAsno": "0124",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금, 은, 유리",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "금속공예",
        "ccbaCncl": "신라 시대의 금관으로, 유리 장식이 남아 있어 당시의 장신구 문화를 보여준다.",
        "ccbaImage": "/images/relic/11/0124.jpg",
        "ccbaSize": "높이 29cm",
    },
    {
        "ccbaMnm1": "마애여래삼존상",
        "ccbaMnm2": "Carved Buddha Triad",
        "ccbaKdcd": "11",
        "ccbaAsno": "0113",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "화강암",
        "ccmaName": "경주시",
        "ccbaClas": "불교 조각",
        "ccbaCncl": "삼국시대 화강암에 새긴 마애여래삼존상으로, 대규모 암각화이다.",
        "ccbaImage": "/images/relic/11/0113.jpg",
        "ccbaSize": "높이 5.5m",
    },
    {
        "ccbaMnm1": "백제 금동대향로",
        "ccbaMnm2": "Baekje Gilt-bronze Censer",
        "ccbaKdcd": "11",
        "ccbaAsno": "0287",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금동",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "불교 신앙器材",
        "ccbaCncl": "백제 시대의 금동대향로로, 고도한 금속 공예 기술을 보여준다.",
        "ccbaImage": "/images/relic/11/0287.jpg",
        "ccbaSize": "높이 30cm",
    },
    {
        "ccbaMnm1": "칠성도",
        "ccbaMnm2": "Chilseongdo",
        "ccbaKdcd": "11",
        "ccbaAsno": "0080",
        "ccbsChrcd": "조선시대",
        "ccmiName": "종이, 채색, 금박",
        "ccmaName": "국립민속박물관",
        "ccbaClas": "민화",
        "ccbaCncl": "조선시대의 민화인 칠성도로, 칠성과 별군을 그렸다.",
        "ccbaImage": "/images/relic/11/0080.jpg",
        "ccbaSize": "가로 120cm, 세로 210cm",
    },
    {
        "ccbaMnm1": "호랑이 그림",
        "ccbaMnm2": "Tiger Painting",
        "ccbaKdcd": "11",
        "ccbaAsno": "0081",
        "ccbsChrcd": "조선시대",
        "ccmiName": "종이, 먹, 채색",
        "ccmaName": "국립민속박물관",
        "ccbaClas": "민화",
        "ccbaCncl": "조선시대의 호랑이 민화로, 힘찬 필치로 호랑이를 그렸다.",
        "ccbaImage": "/images/relic/11/0081.jpg",
        "ccbaSize": "가로 150cm, 세로 80cm",
    },
    {
        "ccbaMnm1": "용왕상",
        "ccbaMnm2": "Dragon King Painting",
        "ccbaKdcd": "11",
        "ccbaAsno": "0082",
        "ccbsChrcd": "조선시대",
        "ccmiName": "종이, 채색",
        "ccmaName": "국립민속박물관",
        "ccbaClas": "민화",
        "ccbaCncl": "조선시대의 용왕상으로, 물의 신을 형상화하였다.",
        "ccbaImage": "/images/relic/11/0082.jpg",
        "ccbaSize": "가로 100cm, 세로 180cm",
    },
    {
        "ccbaMnm1": "물고기 그림",
        "ccbaMnm2": "Fish Painting",
        "ccbaKdcd": "11",
        "ccbaAsno": "0079",
        "ccbsChrcd": "조선시대",
        "ccmiName": "종이, 채색",
        "ccmaName": "국립민속박물관",
        "ccbaClas": "민화",
        "ccbaCncl": "조선시대의 물고기 민화로, 상징적 의미를 담고 있다.",
        "ccbaImage": "/images/relic/11/0079.jpg",
        "ccbaSize": "가로 130cm, 세로 75cm",
    },
    {
        "ccbaMnm1": "수청 황단 및 제기",
        "ccbaMnm2": "Royal Ancestral Ritual Table and Utensils",
        "ccbaKdcd": "11",
        "ccbaAsno": "0135",
        "ccbsChrcd": "조선시대",
        "ccmiName": "나무, 금",
        "ccmaName": "궁능중앙박물관",
        "ccbaClas": "예기도자기",
        "ccbaCncl": "조선 왕실의 제中使用하던 제기와수로, 궁정 문화의 정수를 보여준다.",
        "ccbaImage": "/images/relic/11/0135.jpg",
        "ccbaSize": "가로 160cm, 세로 50cm",
    },
    {
        "ccbaMnm1": "백자 병",
        "ccbaMnm2": "White Porcelain Bottle",
        "ccbaKdcd": "11",
        "ccbaAsno": "0069",
        "ccbsChrcd": "조선시대",
        "ccmiName": "백토",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "도자기",
        "ccbaCncl": "조선시대의 백자 병으로, 검은 점이 특징적인 명작이다.",
        "ccbaImage": "/images/relic/11/0069.jpg",
        "ccbaSize": "높이 22.3cm",
    },
    {
        "ccbaMnm1": "청자 상감학목을 문갑",
        "ccbaMnm2": "Celadon Vase with Crane and Cloud Design",
        "ccbaKdcd": "11",
        "ccbaAsno": "0066",
        "ccbsChrcd": "고려시대",
        "ccmiName": "청자",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "도자기",
        "ccbaCncl": "고려 청자의 상감 기법이 도입된 초기 작품으로, 학목문이 정교하게 새겨졌다.",
        "ccbaImage": "/images/relic/11/0066.jpg",
        "ccbaSize": "높이 19.8cm",
    },
    {
        "ccbaMnm1": "금속활자",
        "ccbaMnm2": "Metal Movable Type",
        "ccbaKdcd": "11",
        "ccbaAsno": "0015",
        "ccbsChrcd": "고려시대",
        "ccmiName": "청동",
        "ccmaName": "한국국학진흥원",
        "ccbaClas": "전적류",
        "ccbaCncl": "고려 시대의 금속활자로, 세계 최고 수준의 인쇄 기술 유산이다.",
        "ccbaImage": "/images/relic/11/0015.jpg",
        "ccbaSize": "가로 7cm, 세로 10cm",
    },
    {
        "ccbaMnm1": "금동 보살 장식",
        "ccbaMnm2": "Gilt-bronze Bodhisattva Ornament",
        "ccbaKdcd": "11",
        "ccbaAsno": "0091",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금동",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "금속공예",
        "ccbaCncl": "삼국시대 보살상 장신구로, 세공이 정교하다.",
        "ccbaImage": "/images/relic/11/0091.jpg",
        "ccbaSize": "길이 35cm",
    },
    {
        "ccbaMnm1": "남산 고분 금관",
        "ccbaMnm2": "Gold Crown from Namsan Tomb",
        "ccbaKdcd": "11",
        "ccbaAsno": "0086",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금, 은",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "금속공예",
        "ccbaCncl": "남산 고분에서 출토된 금관으로, 신라 왕실의 유물이다.",
        "ccbaImage": "/images/relic/11/0086.jpg",
        "ccbaSize": "높이 31cm",
    },
    {
        "ccbaMnm1": "가야 금관",
        "ccbaMnm2": "Gaya Gold Crown",
        "ccbaKdcd": "11",
        "ccbaAsno": "0085",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "금",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "금속공예",
        "ccbaCncl": "가야 왕국의 금관으로, 남아시아와의文化交流를 보여준다.",
        "ccbaImage": "/images/relic/11/0085.jpg",
        "ccbaSize": "높이 18cm",
    },
    {
        "ccbaMnm1": "황토 기",
        "ccbaMnm2": "Yellow Earthenware",
        "ccbaKdcd": "11",
        "ccbaAsno": "0038",
        "ccbsChrcd": "삼국시대",
        "ccmiName": "토기",
        "ccmaName": "국립중앙박물관",
        "ccbaClas": "토기",
        "ccbaCncl": "삼국시대 토기로, 황토색 유약이 특징적이다.",
        "ccbaImage": "/images/relic/11/0038.jpg",
        "ccbaSize": "높이 25cm",
    },
    {
